# from https://github.com/rmiddle/docker-pg_dump

# ARG POSTGRES_VERSION
FROM postgres:12-alpine
# MAINTAINER Robert Middleswarth <72569+rmiddle@users.noreply.github.com> # Previously Cristoffer Fairweather <cfairweather@annixa.com>, Bruno Luiz <contact@brunoluiz.net>

# RUN apt update && \
#     apt install -y cron wget && \
#     apt clean && rm -rf /var/lib/apt/lists/*

# # RUN mkdir ~/.postgresql \ 
# # 	&& wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" -O ~/.postgresql/root.crt \
# # 	&& chmod 0600 ~/.postgresql/root.crt

# ADD dump.sh /dump.sh
# RUN chmod +x /dump.sh

# ADD start.sh /start.sh
# RUN chmod +x /start.sh

# VOLUME /dump

# ENTRYPOINT ["/start.sh"]
# CMD [""]
