version: "3"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

x-env-general: &env-general
  TZ: ${TZ:-Europe/Moscow}

x-env-wiki: &env-wiki
  DB_HOST: ${DB_HOST:-db}
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME: ${DB_NAME:-wiki}
  DB_USER: ${DB_USER:-wikijs}
  DB_PASS: ${DB_PASS:-wikijsrocks}
  DB_TYPE: ${DB_TYPE:-postgres}
  OFFLINE_ACTIVE: ${OFFLINE_ACTIVE:-1}

services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-wiki
      <<: *env-general
    <<: *default
    ports:
      - ${WIKI_PORT:-8000}:3000
    volumes:
      - wiki_temp:/wiki/data
      - /etc/localtime:/etc/localtime:ro
      - ./conf/config.yml:/wiki/config.yml 
    healthcheck:
      test: (curl http://localhost:3000/healthz | grep ok) || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  wiki_temp: